spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sonar
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
